# Generated by Django 4.2.7 on 2025-12-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_video_call_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitallocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospitallocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='patient',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
