import React, {
  createContext,
  useContext,
  useState,
  ReactNode,
  useEffect,
} from "react";

export type Language = "english" | "urdu";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Translation dictionary
const translations = {
  english: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.submitSymptoms": "Get Recommendation",
    "nav.bookAppointment": "Book Appointment",
    "nav.recommendations": "Recommendations",
    "nav.appointments": "My Appointments",
    "nav.documents": "Documents",
    "nav.messages": "Messages",
    "nav.feedback": "Feedback",
    "nav.payments": "Payments",
    "nav.profile": "Profile",
    "nav.signOut": "Sign Out",
    "nav.patientPortal": "Patient Portal",

    // Dashboard
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.youHave": "You have",
    "dashboard.upcomingAppointments": "upcoming appointment",
    "dashboard.upcomingAppointmentsPlural": "upcoming appointments",
    "dashboard.stayHealthy":
      "Stay healthy and keep track of your wellness journey.",
    "dashboard.totalAppointments": "Total Appointments",
    "dashboard.upcomingAppointmentsTitle": "Upcoming Appointments",
    "dashboard.completedFeedback": "Completed Feedback",
    "dashboard.thisMonth": "this month",
    "dashboard.next": "Next",
    "dashboard.pending": "pending",
    "dashboard.noUpcoming": "No upcoming",
    "dashboard.noUpcomingAppointments": "No upcoming appointments.",
    "dashboard.viewAllAppointments": "View all appointments",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.status.upcoming": "upcoming",
    "dashboard.status.completed": "completed",
    "dashboard.status.cancelled": "cancelled",
    "dashboard.mode.online": "Online",
    "dashboard.mode.inPerson": "In-Person",
    "days.monday": "Monday",
    "days.tuesday": "Tuesday",
    "days.wednesday": "Wednesday",
    "days.thursday": "Thursday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.sunday": "Sunday",
    "months.january": "January",
    "months.february": "February",
    "months.march": "March",
    "months.april": "April",
    "months.may": "May",
    "months.june": "June",
    "months.july": "July",
    "months.august": "August",
    "months.september": "September",
    "months.october": "October",
    "months.november": "November",
    "months.december": "December",
    "dashboard.submitSymptoms": "Get Recommendation",
    "dashboard.bookAppointment": "Book Appointment",
    "dashboard.findDoctors": "Find Doctors",
    "dashboard.uploadDocuments": "Upload Documents",

    // Language Toggle
    "language.urdu": "اردو",
    "language.english": "English",

    // Header
    "header.patientDash": "PatientDash",
    "header.patient": "Patient",
    "header.notifications": "Notifications",
    "header.new": "new",
    "header.all": "All",
    "header.system": "System",
    "header.booking": "Booking",
    "header.clearAll": "Clear All",
    "header.noNotifications": "No new notifications.",
    "header.remove": "Remove",
    "header.notification1":
      "Your appointment with Dr. Chen is tomorrow at 10:30.",
    "header.notification2": "Lab results are available in Documents.",
    "header.notification3": "Feedback requested for your last visit.",

    // Profile Page
    "profile.title": "Profile",
    "profile.subtitle": "Manage your personal information and account settings",
    "profile.personalInformation": "Personal Information",
    "profile.editProfile": "Edit Profile",
    "profile.editing": "Editing...",
    "profile.firstName": "First Name",
    "profile.middleName": "Middle Name",
    "profile.lastName": "Last Name",
    "profile.emailAddress": "Email Address",
    "profile.phoneNumber": "Phone Number",
    "profile.age": "Age",
    "profile.gender": "Gender",
    "profile.male": "Male",
    "profile.female": "Female",
    "profile.other": "Other",
    "profile.address": "Address",
    "profile.bloodType": "Blood Type",
    "profile.selectBloodType": "Select Blood Type",
    "profile.emergencyContactName": "Emergency Contact Name",
    "profile.emergencyContactPhone": "Emergency Contact Phone",
    "profile.knownAllergies": "Known Allergies",
    "profile.allergiesPlaceholder": "List any known allergies...",
    "profile.medicalConditions": "Medical Conditions",
    "profile.conditionsPlaceholder": "List any ongoing medical conditions...",
    "profile.accountSettings": "Account Settings",
    "profile.emailNotifications": "Email Notifications",
    "profile.emailNotificationsDesc": "Receive appointment reminders",
    "profile.smsNotifications": "SMS Notifications",
    "profile.smsNotificationsDesc": "Receive text message alerts",
    "profile.marketingEmails": "Marketing Emails",
    "profile.marketingEmailsDesc": "Health tips and promotions",
    "profile.timeFormat": "Time Format",
    "profile.timeFormatDesc": "Choose 12-hour or 24-hour time display",
    "profile.dateFormat": "Date Format",
    "profile.dateFormatDesc": "Choose your preferred date display format",
    "profile.timeFormat12h": "12-hour (2:30 PM)",
    "profile.timeFormat24h": "24-hour (14:30)",
    "profile.dateFormatMDY": "MM-DD-YYYY (12-25-2024)",
    "profile.dateFormatDMY": "DD-MM-YYYY (25-12-2024)",
    "profile.dateFormatYMD": "YYYY-MM-DD (2024-12-25)",
    "profile.upload": "Upload",
    "profile.remove": "Remove",
    "profile.cancel": "Cancel",
    "profile.saveChanges": "Save Changes",
    "profile.keepEditing": "Keep Editing",
    "profile.discard": "Discard",
    "profile.save": "Save",
    "profile.removeProfilePicture": "Remove Profile Picture?",
    "profile.removeProfilePictureConfirm":
      "Are you sure you want to remove your profile picture?",
    "profile.discardChanges": "Discard Changes?",
    "profile.discardChangesConfirm":
      "You have unsaved changes. Are you sure you want to discard them?",
    "profile.saveChangesConfirm": "Save Changes?",
    "profile.saveChangesConfirmText":
      "Are you sure you want to save the changes to your profile?",
    "profile.updatePassword": "Update Password",
    "profile.patientId": "Patient ID",

    // Change Password Section
    "profile.changePassword": "Change Password",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmNewPassword": "Confirm New Password",

    // Feedback Page
    "feedback.title": "Submit Feedback",
    "feedback.subtitle": "Share your experience to help improve our services",
    "feedback.guidelines": "Feedback Guidelines",
    "feedback.guideline1": "Be honest and constructive in your review",
    "feedback.guideline2":
      "Focus on your experience with the doctor and treatment",
    "feedback.guideline3": "Avoid sharing personal medical information",
    "feedback.guideline4": "Keep your review professional and respectful",
    "feedback.selectAppointment": "Select Appointment",
    "feedback.chooseAppointment": "Choose an appointment to review",
    "feedback.overallRating": "Overall Rating",
    "feedback.yourReview": "Your Review",
    "feedback.reviewPlaceholder":
      "Please share your experience with this doctor. Your feedback helps other patients and helps us improve our services...",
    "feedback.minimumCharacters":
      "Minimum 10 characters. Be specific about what went well or what could be improved.",
    "feedback.submitting": "Submitting...",
    "feedback.submitFeedback": "Submit Feedback",
    "feedback.yourReviews": "Your Reviews",
    "feedback.noReviews": "No reviews submitted yet.",
    "feedback.ratingPoor": "Poor - Very unsatisfied",
    "feedback.ratingFair": "Fair - Somewhat unsatisfied",
    "feedback.ratingGood": "Good - Neutral",
    "feedback.ratingVeryGood": "Very Good - Satisfied",
    "feedback.ratingExcellent": "Excellent - Very satisfied",

    // Documents Page
    "documents.title": "Documents",
    "documents.subtitle": "Upload and manage your medical documents",
    "documents.uploadNewDocument": "Upload New Document",
    "documents.dropFilesHere": "Drop files here or click to upload",
    "documents.uploadDescription":
      "Upload your medical documents, test results, prescriptions, and more",
    "documents.chooseFiles": "Choose Files",
    "documents.acceptedFormats": "Accepted Formats",
    "documents.myDocuments": "My Documents",
    "documents.document": "Document",
    "documents.category": "Category",
    "documents.uploadDate": "Upload Date",
    "documents.size": "Size",
    "documents.actions": "Actions",
    "documents.noDocuments": "No documents uploaded",
    "documents.noDocumentsDescription":
      "Upload your first medical document to get started",
    "documents.uploadDocument": "Upload Document",
    "documents.renameFile": "Rename File",
    "documents.selectCategory": "Select Category",
    "documents.cancel": "Cancel",
    "documents.upload": "Upload",
    "documents.deleteDocument": "Delete Document?",
    "documents.deleteConfirmation":
      "Are you sure you want to delete this document?",
    "documents.delete": "Delete",
    "documents.viewDocument": "View Document",
    "documents.close": "Close",
    "documents.previewNotAvailable":
      "Preview not available for this file type.",
    "documents.realAppNote":
      "(In a real app, you would show the actual file here.)",
    "documents.fileNotAllowed": "is not an allowed format.",

    // Recommendations Page
    "recommendations.title": "Book Appointment",
    "recommendations.subtitle":
      "Find and book an appointment with the right doctor for you",
    "recommendations.searchPlaceholder": "Search doctors or specialties...",
    "recommendations.allSpecialties": "All Specialties",
    "recommendations.allRanges": "All Ranges",
    "recommendations.allGenders": "All Genders",
    "recommendations.allRatings": "All Ratings",
    "recommendations.sortBy": "Sort by",
    "recommendations.rating": "Rating",
    "recommendations.experience": "Experience",
    "recommendations.name": "Name",
    "recommendations.favorites": "Favorites",
    "recommendations.fee": "Fee",
    "recommendations.availability": "Availability",
    "recommendations.showing": "Showing",
    "recommendations.doctors": "doctors",
    "recommendations.doctor": "doctor",
    "recommendations.for": "for",
    "recommendations.yearsExperience": "years experience",
    "recommendations.consultationFee": "consultation fee",
    "recommendations.onlineConsultation": "Online",
    "recommendations.inPersonConsultation": "In-Person",
    "recommendations.languages": "Languages",
    "recommendations.bookAppointment": "Book Appointment",
    "recommendations.viewProfile": "View Profile",
    "recommendations.viewSchedule": "View Schedule",
    "recommendations.addToFavorites": "Add to Favorites",
    "recommendations.removeFromFavorites": "Remove from Favorites",
    "recommendations.patientReviews": "Patient Reviews",
    "recommendations.noReviewsYet": "No reviews yet",
    "recommendations.noDoctorsFound": "No doctors found",
    "recommendations.adjustCriteria":
      "Try adjusting your search criteria or filters",
    "recommendations.reviews": "reviews",
    "recommendations.availableToday": "Available today",
    "recommendations.availableTomorrow": "Available tomorrow",
    "recommendations.bookingTitle": "Book Appointment with",
    "recommendations.selectDate": "Select Date",
    "recommendations.selectTime": "Select Time",
    "recommendations.symptoms": "Symptoms (Optional)",
    "recommendations.symptomsPlaceholder": "Describe your symptoms...",
    "recommendations.confirmBooking": "Confirm Booking",
    "recommendations.cancel": "Cancel",
    "booking.step1": "Step 1: Select Appointment Mode",
    "booking.step2": "Step 2",
    "booking.step3": "Step 3",
    "booking.step4": "Step 4",
    "booking.online": "Online",
    "booking.inPerson": "In-Person",
    "booking.videoConsultation": "Video Consultation",
    "booking.clinicVisit": "Clinic Visit",
    "booking.notAvailable": "Not Available",
    "booking.selectLocation": "Select Location",
    "booking.selectADate": "Select a date",
    "booking.selectDateFirst": "Select a date first",
    "booking.selectTime": "Select time...",
    "booking.booking": "Booking...",
    "booking.proceedToPayment": "Proceed to Payment",
    "payment.paymentRequired": "Payment Required",
    "payment.paymentSuccessful": "Payment Successful!",
    "payment.appointmentConfirming": "Your appointment is being confirmed...",
    "payment.appointmentSummary": "Appointment Summary",
    "payment.doctor": "Doctor",
    "payment.mode": "Mode",
    "payment.consultationFee": "Consultation Fee",
    "payment.selectPaymentMethod": "Select Payment Method",
    "payment.addNewPaymentMethod": "Add New Payment Method",
    "payment.processingPayment": "Processing Payment...",
    "payment.payAmount": "Pay Rs.",
    "payment.secureNote": "Your payment information is secure and encrypted",
    "appointments.title": "My Appointments",
    "appointments.subtitle": "View and manage your appointments",
    "appointments.upcoming": "Upcoming",
    "appointments.completed": "Completed",
    "appointments.cancelled": "Cancelled",
    "appointments.all": "All",
    "appointments.viewDoctor": "View Doctor",
    "appointments.message": "Message",
    "appointments.cancel": "Cancel",
    "appointments.symptoms": "Symptoms",
    "appointments.showLess": "Show less",
    "appointments.readMore": "Read more",
    "appointments.followUp": "Follow-up",
    "appointments.rescheduledByAdmin": "Rescheduled by Admin",
    "appointments.rescheduledByDoctor": "Rescheduled by Doctor",
    "appointments.rescheduled": "Rescheduled",
    "appointments.viewReason": "View Reason",
    "appointments.cancelledByYou": "Cancelled by You",
    "appointments.cancelledByDoctor": "Cancelled by Doctor",
    "appointments.cancelledByAdmin": "Cancelled by Admin",
    "appointments.cancelAppointmentTitle": "Cancel Appointment",
    "appointments.cancelConfirm":
      "Are you sure you want to cancel this appointment?",
    "appointments.noRefundPolicy": "No Refund Policy",
    "appointments.noRefundMessage":
      "Patient cancellations are not eligible for refunds. The payment will not be returned.",
    "appointments.reasonForCancellation": "Reason for cancellation (optional)",
    "appointments.cancellationPlaceholder":
      "Let us know why you're cancelling...",
    "appointments.noKeepIt": "No, Keep It",
    "appointments.yesCancel": "Yes, Cancel",
    "appointments.cancelling": "Cancelling...",
    "appointments.loadMore": "Load More",
    "appointments.noAppointmentsFound": "No Appointments Found",
    "appointments.doctorUnavailable": "This doctor is currently unavailable",
    "appointments.doctorBlockedMessage":
      "The doctor has been temporarily blocked by the administrator. Your appointment may need to be rescheduled.",
    "appointments.noReasonProvided": "No reason provided",
    "appointments.rescheduledAppointment": "Rescheduled appointment",
    "appointments.status.upcoming": "Upcoming",
    "appointments.status.completed": "Completed",
    "appointments.status.cancelled": "Cancelled",
    "appointments.onlineConsultation": "Online Consultation",
    "appointments.inPersonConsultation": "In-Person Consultation",
    "appointments.appointmentDetails": "Appointment Details",
    "appointments.date": "Date",
    "appointments.time": "Time",
    "appointments.location": "Location",
    "appointments.reason": "Reason",
    "appointments.viewSchedule": "View Schedule",
    "appointments.hideSchedule": "Hide Schedule",
    "appointments.viewFeedback": "View Feedback",
    "appointments.hideFeedback": "Hide Feedback",
    "appointments.bookAppointment": "Book Appointment",
    "call.callingForVideo": "Calling for video consultation...",
    "call.accept": "Accept",
    "call.decline": "Decline",
    "call.answerCallTitle": "Answer Call",
    "call.answerCallConfirm": "Are you sure you want to answer the call from",
    "call.answer": "Answer",
    "call.cancel": "Cancel",
    "call.declineCallTitle": "Decline Call",
    "call.declineCallConfirm": "Are you sure you want to decline the call from",
    "call.documentSharingRequest": "Document Sharing Request",
    "call.documentSharingMessage":
      "is requesting access to view your medical documents. Would you like to share your documents?",
    "call.yes": "Yes",
    "call.no": "No",
    "call.documentRequestTitle": "Document Request",
    "call.documentRequestMessage":
      "has requested to view your medical documents. Please select the documents you wish to share:",
    "call.noDocuments": "No documents available to share",
    "call.shareSelected": "Share Selected",
    "call.documentsSharedTitle": "Documents Shared",
    "call.documentsSharedMessage": "You have successfully shared",
    "call.documentsSharedWith": "with the doctor",
    "call.document": "document",
    "call.documents": "documents",
    "call.ok": "OK",
    "call.prescriptionUploadedTitle": "Prescription Uploaded",
    "call.prescriptionUploadedMessage":
      "The doctor has uploaded your prescription. You can view it in your documents section.",
    "call.completeConsultationTitle": "Complete Consultation",
    "call.noPrescriptionWarning":
      "⚠️ The doctor hasn't uploaded a prescription yet.",
    "call.completionRequestMessage":
      "has requested to complete the consultation. Do you agree to complete the consultation?",
    "call.yes": "Yes",
    "call.no": "No",
    "call.consultationFinishedTitle": "Consultation Finished",
    "call.consultationFinishedMessage":
      "Your consultation has been completed successfully.",
    "call.endCallTitle": "End Call",
    "call.noPrescriptionWarningEnd":
      "⚠️ The doctor hasn't uploaded a prescription yet.",
    "call.endCallConfirmation": "Are you sure you want to end this call with",
    "call.cancel": "Cancel",
    "call.endCall": "End Call",
    "call.callEndedTitle": "Call Ended",
    "call.callEndedMessage": "has ended the call.",
    "call.callEndedByYouTitle": "Call Ended",
    "call.callEndedByYouMessage": "You have ended the call.",
    "payments.title": "Payments",
    "payments.subtitle":
      "Manage your payments, transaction history, and payment methods",
    "payments.overview": "Overview",
    "payments.transactions": "Transactions",
    "payments.paymentMethods": "Payment Methods",
    "payments.requests": "Requests",
    "payments.totalSpent": "Total Spent",
    "payments.availableBalance": "Available Balance",
    "payments.pendingPayments": "Pending Payments",
    "payments.paymentRequests": "Payment Requests",
    "payments.recentTransactions": "Recent Transactions",
    "payments.searchPlaceholder": "Search by doctor name or appointment ID...",
    "payments.filterByStatus": "Filter by Status",
    "payments.all": "All",
    "payments.completed": "Completed",
    "payments.pending": "Pending",
    "payments.refunded": "Refunded",
    "payments.export": "Export",
    "payments.exportCSV": "Export to CSV",
    "payments.exportExcel": "Export to Excel",
    "payments.noTransactions": "No transactions found",
    "payments.transactionId": "Transaction ID",
    "payments.appointmentId": "Appointment ID",
    "payments.doctor": "Doctor",
    "payments.date": "Date",
    "payments.amount": "Amount",
    "payments.mode": "Mode",
    "payments.status": "Status",
    "payments.paymentMethod": "Payment Method",
    "payments.online": "Online",
    "payments.inPerson": "In-person",
    "payments.addPaymentMethod": "Add Payment Method",
    "payments.noPaymentMethods": "No payment methods added yet",
    "payments.addFirstMethod":
      "Add your first payment method to make payments easier",
    "payments.bankAccount": "Bank Account",
    "payments.mobileWallet": "Mobile Wallet",
    "payments.accountNumber": "Account Number",
    "payments.iban": "IBAN",
    "payments.phoneNumber": "Phone Number",
    "payments.default": "Default",
    "payments.setDefault": "Set as Default",
    "payments.edit": "Edit",
    "payments.delete": "Delete",
    "payments.addMethod": "Add Method",
    "payments.cancel": "Cancel",
    "payments.save": "Save",
    "payments.methodType": "Method Type",
    "payments.methodName": "Method Name",
    "payments.deleteConfirmTitle": "Delete Payment Method",
    "payments.deleteConfirmMessage":
      "Are you sure you want to delete this payment method?",
    "payments.noRequests": "No payment requests",
    "payments.allRequestsProcessed": "All payment requests have been processed",
    "payments.appointmentType": "Appointment Type",
    "payments.reason": "Reason",
    "payments.payNow": "Pay Now",
    "payments.decline": "Decline",
    "payments.paid": "Paid",
    "payments.declined": "Declined",
    "payments.confirmPayment": "Confirm Payment",
    "payments.selectPaymentMethod": "Select a payment method",
    "payments.confirmPaymentMessage": "Are you sure you want to pay",
    "payments.for": "for",
    "payments.declineRequest": "Decline Payment Request",
    "payments.declineConfirmMessage":
      "Are you sure you want to decline this payment request?",
    "payments.success": "Success",
    "payments.error": "Error",
    "payments.paymentSuccessMessage": "Payment completed successfully!",
    "payments.paymentErrorMessage":
      "Failed to process payment. Please try again.",
    "payments.requestDeclined": "Payment request declined",
    "payments.methodAdded": "Payment method added successfully",
    "payments.methodDeleted": "Payment method deleted successfully",
    "payments.methodUpdated": "Payment method updated successfully",
    "payments.requestsTitle": "Payment Requests",
    "payments.requestsSubtitle":
      "Follow-up consultation and additional payment requests",
    "payments.appointmentDetails": "Appointment Details",
    "payments.requested": "Requested",
    "payments.rescheduleReason": "Reschedule Reason",
    "payments.noRequestsTitle": "No Payment Requests",
    "payments.noRequestsMessage":
      "You have no pending payment requests at the moment",
    "payments.paymentMethodsTitle": "Payment Methods",
    "payments.addMethodsPrompt": "Add 1-5 payment methods for appointments",
    "payments.maxLimitReached": "Maximum limit reached (5/5)",
    "payments.methodsAdded": "payment methods added",
    "payments.addNewMethod": "Add New Payment Method",
    "payments.selectBank": "Select Bank",
    "payments.enterAccountNumber": "Enter account number (10-20 digits)",
    "payments.enterIBAN": "Enter IBAN (PK followed by 22 digits)",
    "payments.selectWallet": "Select Mobile Wallet",
    "payments.enterPhoneNumber": "Enter phone number (03XXXXXXXXX)",
    "payments.removeMethodTitle": "Remove Payment Method",
    "payments.removeMethodMessage":
      "Are you sure you want to remove this payment method? This action cannot be undone.",
    "payments.followUp": "Follow-up",
    "recommendations.bookingSuccess": "Appointment booked successfully!",
    "recommendations.bookingSuccessMessage":
      "Your appointment has been confirmed with",
    "recommendations.date": "Date",
    "recommendations.time": "Time",
    "recommendations.close": "Close",
    "recommendations.education": "Education",
    "recommendations.certifications": "Certifications",
    "recommendations.bio": "About",
    "recommendations.workingHours": "Working Hours",
    "recommendations.contact": "Contact Information",

    // Messages Page
    "messages.title": "Messages",
    "messages.subtitle": "Communicate with your doctors",
    "messages.searchDoctors": "Search doctors...",
    "messages.noDoctorsFound": "No doctors found",
    "messages.noMessages": "No messages yet. Start a conversation!",
    "messages.typeMessage": "Type your message...",
    "messages.selectDoctor": "Select a doctor to start messaging",

    // Symptoms Page - Categories
    "symptoms.categoryGeneral": "General Symptoms",
    "symptoms.categorySkin": "Skin Problems",
    "symptoms.categoryStomach": "Stomach & Digestion",
    "symptoms.categoryBreathing": "Breathing & Chest",
    "symptoms.categoryUrinary": "Urinary Problems",
    "symptoms.categoryEyes": "Eyes & Vision",
    "symptoms.categoryBrain": "Brain & Nerves",
    "symptoms.categoryBones": "Bones & Joints",
    "symptoms.categoryMental": "Mental Health",
    "symptoms.categoryLiver": "Liver Symptoms",
    "symptoms.categoryHeart": "Heart Related",
    "symptoms.categoryHormonal": "Hormonal Issues",
    "symptoms.categoryRectal": "Rectal Problems",
    "symptoms.categoryOther": "Other Symptoms",

    // Symptoms Page - Interface
    "symptoms.title": "Submit Symptoms",
    "symptoms.subtitle":
      "Describe your symptoms to get personalized doctor recommendations",
    "symptoms.selectedSymptoms": "Your Selected Symptoms",
    "symptoms.clearAll": "Clear all",
    "symptoms.browseSymptoms": "Browse Symptoms",
    "symptoms.searchPlaceholder":
      "Search symptoms (e.g., fever, headache, cough...)",
    "symptoms.noSymptomsFound": "No symptoms found matching",
    "symptoms.clearSearch": "Clear search",
    "symptoms.selected": "selected",
    "symptoms.symptoms": "symptoms",
    "symptoms.of": "of",
    "symptoms.howItWorks": "How it works",
    "symptoms.step1": "Select symptoms from categories or search",
    "symptoms.step2": "Review your selections at the top",
    "symptoms.step3": "Submit to get doctor recommendations",
    "symptoms.readyToSubmit": "Ready to Submit!",
    "symptoms.youveSelected": "You've selected",
    "symptoms.symptom": "symptom",
    "symptoms.getRecommendation": "Get Specialist Recommendation",
    "symptoms.analyzing": "Analyzing...",
    "symptoms.findingBest": "Finding the best doctors for you",
    "symptoms.confirmTitle": "Confirm Selected Symptoms",
    "symptoms.confirmMessage":
      "You have selected the following symptoms. Please confirm to get specialist recommendation:",
    "symptoms.total": "Total",
    "symptoms.cancel": "Cancel",
    "symptoms.confirmButton": "Confirm & Get Recommendation",
    "symptoms.predictionError": "Prediction Error",
    "symptoms.recommendedSpecialist": "Recommended Specialist",
    "symptoms.basedOnSymptoms": "Based on your symptoms, you should consult:",
    "symptoms.found": "Found",
    "symptoms.doctor": "doctor",
    "symptoms.doctors": "doctors",
    "symptoms.available": "available",
    "symptoms.clickToSearch":
      "Click below to search for available doctors in this specialty",
    "symptoms.viewRankedDoctors": "View Ranked Doctors",
    "symptoms.searchForDoctors": "Search for Doctors",
    "symptoms.close": "Close",
    "symptoms.ok": "OK",
    "symptoms.rankedDoctors": "Ranked Doctors",
    "symptoms.specialty": "Specialty",
    "symptoms.noDoctorsAvailable": "No Doctors Available",
    "symptoms.couldntFind":
      "We couldn't find any approved doctors specializing in",
    "symptoms.atMoment": "at the moment.",
    "symptoms.whatCanYouDo": "What can you do?",
    "symptoms.tryAgainLater":
      "Try again later - new doctors may join the platform",
    "symptoms.browseAll":
      "Browse all available doctors in the Recommendations section",
    "symptoms.contactSupport": "Contact support if you need urgent assistance",
    "symptoms.showing": "Showing",
    "symptoms.rating": "Rating",
    "symptoms.experience": "Experience",
    "symptoms.year": "year",
    "symptoms.years": "years",
    "symptoms.matchScore": "Match Score",
    "symptoms.email": "Email",
    "symptoms.phone": "Phone",
    "symptoms.consultationFee": "Consultation Fee",
    "symptoms.viewDetailsBook": "View Details & Book",
    "symptoms.review": "review",
    "symptoms.reviews": "reviews",
  },
  urdu: {
    // Navigation
    "nav.dashboard": "ڈیش بورڈ",
    "nav.submitSymptoms": "مشورہ حاصل کریں",
    "nav.bookAppointment": "ملاقات بک کریں",
    "nav.recommendations": "ڈاکٹر تلاش کریں",
    "nav.appointments": "میری ملاقاتیں",
    "nav.documents": "دستاویزات",
    "nav.messages": "پیغامات",
    "nav.feedback": "رائے",
    "nav.payments": "ادائیگیاں",
    "nav.profile": "پروفائل",
    "nav.signOut": "سائن آؤٹ",
    "nav.patientPortal": "مریض پورٹل",

    // Dashboard
    "dashboard.welcomeBack": "خوش آمدید",
    "dashboard.youHave": "آپ کی",
    "dashboard.upcomingAppointments": "آنے والی ملاقات ہے",
    "dashboard.upcomingAppointmentsPlural": "آنے والی ملاقاتیں ہیں",
    "dashboard.stayHealthy":
      "صحت مند رہیں اور اپنی تندرستی کے سفر کو ٹریک کریں۔",
    "dashboard.totalAppointments": "کل ملاقاتیں",
    "dashboard.upcomingAppointmentsTitle": "آنے والی ملاقاتیں",
    "dashboard.completedFeedback": "مکمل شدہ رائے",
    "dashboard.thisMonth": "اس ماہ",
    "dashboard.next": "اگلا",
    "dashboard.pending": "باقی",
    "dashboard.noUpcoming": "کوئی آنے والی نہیں",
    "dashboard.noUpcomingAppointments": "کوئی آنے والی ملاقات نہیں۔",
    "dashboard.viewAllAppointments": "تمام ملاقاتیں دیکھیں",
    "dashboard.quickActions": "فوری رسائی",
    "dashboard.status.upcoming": "آنے والی",
    "dashboard.status.completed": "مکمل",
    "dashboard.status.cancelled": "منسوخ",
    "dashboard.mode.online": "آن لائن",
    "dashboard.mode.inPerson": "ذاتی ملاقات",
    "days.monday": "پیر",
    "days.tuesday": "منگل",
    "days.wednesday": "بدھ",
    "days.thursday": "جمعرات",
    "days.friday": "جمعہ",
    "days.saturday": "ہفتہ",
    "days.sunday": "اتوار",
    "months.january": "جنوری",
    "months.february": "فروری",
    "months.march": "مارچ",
    "months.april": "اپریل",
    "months.may": "مئی",
    "months.june": "جون",
    "months.july": "جولائی",
    "months.august": "اگست",
    "months.september": "ستمبر",
    "months.october": "اکتوبر",
    "months.november": "نومبر",
    "months.december": "دسمبر",
    "dashboard.submitSymptoms": "سفارش حاصل کریں",
    "dashboard.bookAppointment": "ملاقات بک کریں",
    "dashboard.findDoctors": "ڈاکٹر تلاش کریں",
    "dashboard.uploadDocuments": "دستاویزات اپ لوڈ کریں",

    // Language Toggle
    "language.urdu": "اردو",
    "language.english": "English",

    // Header
    "header.patientDash": "مریض ڈیش",
    "header.patient": "مریض",
    "header.notifications": "اطلاعات",
    "header.new": "نئے",
    "header.all": "تمام",
    "header.system": "سسٹم",
    "header.booking": "بکنگ",
    "header.clearAll": "سب صاف کریں",
    "header.noNotifications": "کوئی نئی اطلاع نہیں۔",
    "header.remove": "ہٹائیں",
    "header.notification1": "ڈاکٹر چن کے ساتھ آپ کی ملاقات کل ۱۰:۳۰ بجے ہے۔",
    "header.notification2": "لیب کے نتائج دستاویزات میں دستیاب ہیں۔",
    "header.notification3": "آپ کے آخری دورے کے لیے رائے درخواست کی گئی ہے۔",

    // Profile Page
    "profile.title": "پروفائل",
    "profile.subtitle": "اپنی ذاتی معلومات اور اکاؤنٹ کی سیٹنگز کا انتظام کریں",
    "profile.personalInformation": "ذاتی معلومات",
    "profile.editProfile": "پروفائل ایڈٹ کریں",
    "profile.editing": "ایڈٹ کر رہے ہیں...",
    "profile.firstName": "پہلا نام",
    "profile.middleName": "درمیانی نام",
    "profile.lastName": "آخری نام",
    "profile.emailAddress": "ای میل ایڈریس",
    "profile.phoneNumber": "فون نمبر",
    "profile.age": "عمر",
    "profile.gender": "جنس",
    "profile.male": "مرد",
    "profile.female": "عورت",
    "profile.other": "دیگر",
    "profile.address": "پتہ",
    "profile.bloodType": "خون کی قسم",
    "profile.selectBloodType": "خون کی قسم منتخب کریں",
    "profile.emergencyContactName": "ایمرجنسی رابطہ کا نام",
    "profile.emergencyContactPhone": "ایمرجنسی رابطہ فون",
    "profile.knownAllergies": "معلوم الرجیز",
    "profile.allergiesPlaceholder": "کوئی بھی معلوم الرجی کی فہرست بنائیں...",
    "profile.medicalConditions": "طبی حالات",
    "profile.conditionsPlaceholder":
      "کوئی بھی جاری طبی حالات کی فہرست بنائیں...",
    "profile.accountSettings": "اکاؤنٹ سیٹنگز",
    "profile.emailNotifications": "ای میل اطلاعات",
    "profile.emailNotificationsDesc": "ملاقات کی یاد دہانی حاصل کریں",
    "profile.smsNotifications": "SMS اطلاعات",
    "profile.smsNotificationsDesc": "ٹیکسٹ میسج الرٹ حاصل کریں",
    "profile.marketingEmails": "مارکیٹنگ ای میلز",
    "profile.marketingEmailsDesc": "صحت کے نکات اور پروموشن",
    "profile.timeFormat": "وقت کا فارمیٹ",
    "profile.timeFormatDesc": "12-گھنٹے یا 24-گھنٹے وقت ڈسپلے منتخب کریں",
    "profile.dateFormat": "تاریخ کا فارمیٹ",
    "profile.dateFormatDesc": "اپنا پسندیدہ تاریخ ڈسپلے فارمیٹ منتخب کریں",
    "profile.timeFormat12h": "12-گھنٹے (2:30 PM)",
    "profile.timeFormat24h": "24-گھنٹے (14:30)",
    "profile.dateFormatMDY": "MM-DD-YYYY (12-25-2024)",
    "profile.dateFormatDMY": "DD-MM-YYYY (25-12-2024)",
    "profile.dateFormatYMD": "YYYY-MM-DD (2024-12-25)",
    "profile.upload": "اپ لوڈ",
    "profile.remove": "ہٹائیں",
    "profile.cancel": "منسوخ",
    "profile.saveChanges": "تبدیلیاں محفوظ کریں",
    "profile.keepEditing": "ایڈٹ کرتے رہیں",
    "profile.discard": "منسوخ کریں",
    "profile.save": "محفوظ کریں",
    "profile.removeProfilePicture": "پروفائل تصویر ہٹائیں؟",
    "profile.removeProfilePictureConfirm":
      "کیا آپ واقعی اپنی پروفائل تصویر ہٹانا چاہتے ہیں؟",
    "profile.discardChanges": "تبدیلیاں منسوخ کریں؟",
    "profile.discardChangesConfirm":
      "آپ کے پاس غیر محفوظ تبدیلیاں ہیں۔ کیا آپ واقعی انہیں منسوخ کرنا چاہتے ہیں؟",
    "profile.saveChangesConfirm": "تبدیلیاں محفوظ کریں؟",
    "profile.saveChangesConfirmText":
      "کیا آپ واقعی اپنے پروفائل کی تبدیلیاں محفوظ کرنا چاہتے ہیں؟",
    "profile.updatePassword": "پاس ورڈ اپڈیٹ کریں",
    "profile.patientId": "مریض کی شناخت",

    // Change Password Section
    "profile.changePassword": "پاس ورڈ تبدیل کریں",
    "profile.currentPassword": "موجودہ پاس ورڈ",
    "profile.newPassword": "نیا پاس ورڈ",
    "profile.confirmNewPassword": "نیا پاس ورڈ کی تصدیق کریں",

    // Feedback Page
    "feedback.title": "رائے جمع کریں",
    "feedback.subtitle":
      "ہماری خدمات کو بہتر بنانے کے لیے اپنا تجربہ شیئر کریں",
    "feedback.guidelines": "رائے دینے کے اصول",
    "feedback.guideline1": "اپنی رائے میں ایمانداری اور تعمیری انداز اپنائیں",
    "feedback.guideline2": "ڈاکٹر اور علاج کے ساتھ اپنے تجربے پر توجہ دیں",
    "feedback.guideline3": "ذاتی طبی معلومات شیئر کرنے سے بچیں",
    "feedback.guideline4": "اپنی رائے کو پیشہ ورانہ اور احترام کے ساتھ رکھیں",
    "feedback.selectAppointment": "ملاقات منتخب کریں",
    "feedback.chooseAppointment": "رائے دینے کے لیے ایک ملاقات منتخب کریں",
    "feedback.overallRating": "مجموعی درجہ بندی",
    "feedback.yourReview": "آپ کی رائے",
    "feedback.reviewPlaceholder":
      "براہ کرم اس ڈاکٹر کے ساتھ اپنا تجربہ شیئر کریں۔ آپ کی رائے دوسرے مریضوں کی مدد کرتی ہے اور ہماری خدمات کو بہتر بناتی ہے...",
    "feedback.minimumCharacters":
      "کم از کم 10 حروف۔ اس بات کا تفصیل سے ذکر کریں کہ کیا اچھا رہا یا کیا بہتر ہو سکتا ہے۔",
    "feedback.submitting": "جمع کر رہے ہیں...",
    "feedback.submitFeedback": "رائے جمع کریں",
    "feedback.yourReviews": "آپ کی رائے",
    "feedback.noReviews": "ابھی تک کوئی رائے جمع نہیں کی گئی۔",
    "feedback.ratingPoor": "ناکافی - بہت غیر مطمئن",
    "feedback.ratingFair": "ٹھیک ٹھاک - کچھ غیر مطمئن",
    "feedback.ratingGood": "اچھا - غیر جانبدار",
    "feedback.ratingVeryGood": "بہت اچھا - مطمئن",
    "feedback.ratingExcellent": "بہترین - بہت مطمئن",

    // Documents Page
    "documents.title": "دستاویزات",
    "documents.document": "دستاویز",
    "documents.subtitle": "اپنی طبی دستاویزات اپ لوڈ اور منظم کریں",
    "documents.uploadNewDocument": "نئی دستاویز اپ لوڈ کریں",
    "documents.dropFilesHere": "فائلیں یہاں رکھیں",
    "documents.uploadDescription":
      "اپنی طبی دستاویزات، ٹیسٹ کے نتائج، نسخے اور مزید اپ لوڈ کریں",
    "documents.chooseFiles": "فائلیں منتخب کریں",
    "documents.acceptedFormats": "قبول شدہ فارمیٹس",
    "documents.myDocuments": "میری دستاویزات",
    "documents.category": "قسم",
    "documents.uploadDate": "اپ لوڈ کی تاریخ",
    "documents.size": "سائز",
    "documents.actions": "عمل",
    "documents.noDocuments": "کوئی دستاویز اپ لوڈ نہیں کی گئی",
    "documents.noDocumentsDescription":
      "شروعات کرنے کے لیے اپنی پہلی طبی دستاویز اپ لوڈ کریں",
    "documents.uploadDocument": "دستاویز اپ لوڈ کریں",
    "documents.renameFile": "فائل کا نام تبدیل کریں",
    "documents.selectCategory": "قسم منتخب کریں",
    "documents.cancel": "منسوخ",
    "documents.upload": "اپ لوڈ",
    "documents.deleteDocument": "دستاویز ہٹائیں؟",
    "documents.deleteConfirmation":
      "کیا آپ واقعی اس دستاویز کو ہٹانا چاہتے ہیں؟",
    "documents.delete": "ہٹائیں",
    "documents.viewDocument": "دستاویز دیکھیں",
    "documents.close": "بند کریں",
    "documents.previewNotAvailable":
      "اس فائل کی قسم کے لیے پیش منظر دستیاب نہیں۔",
    "documents.realAppNote": "(حقیقی ایپ میں، آپ یہاں اصل فائل دکھائیں گے۔)",
    "documents.fileNotAllowed": "کی اجازت شدہ فارمیٹ نہیں ہے۔",

    // Appointments Page
    "appointments.title": "میری ملاقاتیں",
    "appointments.subtitle": "اپنی موجودہ اور پچھلی ملاقاتوں کا انتظام کریں",
    "appointments.upcoming": "آنے والی",
    "appointments.completed": "مکمل",
    "appointments.cancelled": "منسوخ",
    "appointments.all": "تمام",
    "appointments.type": "قسم",
    "appointments.symptoms": "علامات",
    "appointments.followUp": "فالو اپ",
    "appointments.cancel": "منسوخ کریں",
    "appointments.cancelConfirmation":
      "کیا آپ واقعی اس ملاقات کو منسوخ کرنا چاہتے ہیں؟",
    "appointments.no": "نہیں",
    "appointments.yesCancel": "ہاں، منسوخ کریں",
    "appointments.viewDetails": "تفصیلات دیکھیں",
    "appointments.doctorsNote": "ڈاکٹر کا نوٹ",
    "appointments.noNoteAvailable": "کوئی نوٹ دستیاب نہیں۔",
    "appointments.close": "بند کریں",
    "appointments.giveFeedback": "رائے دیں",
    "appointments.reschedule": "دوبارہ وقت مقرر کریں",
    "appointments.rescheduleTitle": "ملاقات کا وقت تبدیل کریں",
    "appointments.selectDate": "تاریخ منتخب کریں",
    "appointments.selectTime": "وقت منتخب کریں",
    "appointments.confirm": "تصدیق کریں",
    "appointments.noAppointmentsFound": "کوئی ملاقات نہیں ملی",
    "appointments.noAppointmentsYet": "ابھی تک آپ کی کوئی ملاقات نہیں ہے۔",
    "appointments.noAppointmentsOfType": "آپ کی کوئی {type} ملاقات نہیں ہے۔",
    "appointments.findDoctors": "ڈاکٹر تلاش کریں",
    "appointments.cancelAppointmentTitle": "ملاقات منسوخ کریں؟",

    // Recommendations Page
    "recommendations.title": "ملاقات بک کریں",
    "recommendations.subtitle":
      "اپنے لیے صحیح ڈاکٹر تلاش کریں اور ملاقات بک کریں",
    "recommendations.searchPlaceholder": "ڈاکٹر یا ماہرین تلاش کریں...",
    "recommendations.allSpecialties": "تمام ماہرین",
    "recommendations.allRanges": "تمام رینج",
    "recommendations.allGenders": "تمام جنس",
    "recommendations.allRatings": "تمام ریٹنگ",
    "recommendations.sortBy": "ترتیب دیں",
    "recommendations.rating": "ریٹنگ",
    "recommendations.experience": "تجربہ",
    "recommendations.name": "نام",
    "recommendations.favorites": "پسندیدہ",
    "recommendations.fee": "فیس",
    "recommendations.availability": "دستیابی",
    "recommendations.showing": "دکھا رہے ہیں",
    "recommendations.doctors": "ڈاکٹرز",
    "recommendations.doctor": "ڈاکٹر",
    "recommendations.for": "کے لیے",
    "recommendations.yearsExperience": "سال تجربہ",
    "recommendations.consultationFee": "مشاورت کی فیس",
    "recommendations.onlineConsultation": "آن لائن",
    "recommendations.inPersonConsultation": "ذاتی ملاقات",
    "recommendations.languages": "زبانیں",
    "recommendations.bookAppointment": "ملاقات بک کریں",
    "recommendations.viewProfile": "پروفائل دیکھیں",
    "recommendations.viewSchedule": "شیڈول دیکھیں",
    "recommendations.addToFavorites": "پسندیدہ میں شامل کریں",
    "recommendations.removeFromFavorites": "پسندیدہ سے ہٹائیں",
    "recommendations.patientReviews": "مریضوں کے جائزے",
    "recommendations.noReviewsYet": "ابھی تک کوئی جائزہ نہیں",
    "recommendations.noDoctorsFound": "کوئی ڈاکٹر نہیں ملا",
    "recommendations.adjustCriteria":
      "اپنے تلاش کے معیار یا فلٹرز کو تبدیل کرنے کی کوشش کریں",
    "recommendations.reviews": "جائزے",
    "recommendations.availableToday": "آج دستیاب",
    "recommendations.availableTomorrow": "کل دستیاب",
    "recommendations.bookingTitle": "ملاقات بک کریں",
    "recommendations.selectDate": "تاریخ منتخب کریں",
    "recommendations.selectTime": "وقت منتخب کریں",
    "recommendations.symptoms": "علامات (اختیاری)",
    "recommendations.symptomsPlaceholder": "اپنی علامات بیان کریں...",
    "recommendations.confirmBooking": "بکنگ کی تصدیق کریں",
    "recommendations.cancel": "منسوخ",
    "booking.step1": "مرحلہ ۱: ملاقات کی قسم منتخب کریں",
    "booking.step2": "مرحلہ ۲",
    "booking.step3": "مرحلہ ۳",
    "booking.step4": "مرحلہ ۴",
    "booking.online": "آن لائن",
    "booking.inPerson": "ذاتی ملاقات",
    "booking.videoConsultation": "ویڈیو مشاورت",
    "booking.clinicVisit": "کلینک ملاقات",
    "booking.notAvailable": "دستیاب نہیں",
    "booking.selectLocation": "جگہ منتخب کریں",
    "booking.selectADate": "تاریخ منتخب کریں",
    "booking.selectDateFirst": "پہلے تاریخ منتخب کریں",
    "booking.selectTime": "وقت منتخب کریں...",
    "booking.booking": "بک کیا جا رہا ہے...",
    "booking.proceedToPayment": "ادائیگی کی طرف بڑھیں",
    "payment.paymentRequired": "ادائیگی درکار ہے",
    "payment.paymentSuccessful": "ادائیگی کامیاب!",
    "payment.appointmentConfirming": "آپ کی ملاقات کی تصدیق کی جا رہی ہے...",
    "payment.appointmentSummary": "ملاقات کا خلاصہ",
    "payment.doctor": "ڈاکٹر",
    "payment.mode": "قسم",
    "payment.consultationFee": "مشاورت کی فیس",
    "payment.selectPaymentMethod": "ادائیگی کا طریقہ منتخب کریں",
    "payment.addNewPaymentMethod": "نیا ادائیگی کا طریقہ شامل کریں",
    "payment.processingPayment": "ادائیگی پر عمل کیا جا رہا ہے...",
    "payment.payAmount": "ادا کریں Rs.",
    "payment.secureNote": "آپ کی ادائیگی کی معلومات محفوظ اور خفیہ کاری شدہ ہے",
    "appointments.title": "میری ملاقاتیں",
    "appointments.subtitle": "اپنی ملاقاتوں کو دیکھیں اور انتظام کریں",
    "appointments.upcoming": "آنے والی",
    "appointments.completed": "مکمل",
    "appointments.cancelled": "منسوخ",
    "appointments.all": "تمام",
    "appointments.viewDoctor": "ڈاکٹر دیکھیں",
    "appointments.message": "پیغام",
    "appointments.cancel": "منسوخ کریں",
    "appointments.symptoms": "علامات",
    "appointments.showLess": "کم دکھائیں",
    "appointments.readMore": "مزید پڑھیں",
    "appointments.followUp": "فالو اپ",
    "appointments.rescheduledByAdmin": "ایڈمن نے دوبارہ شیڈول کیا",
    "appointments.rescheduledByDoctor": "ڈاکٹر نے دوبارہ شیڈول کیا",
    "appointments.rescheduled": "دوبارہ شیڈول کیا گیا",
    "appointments.viewReason": "وجہ دیکھیں",
    "appointments.cancelledByYou": "آپ نے منسوخ کیا",
    "appointments.cancelledByDoctor": "ڈاکٹر نے منسوخ کیا",
    "appointments.cancelledByAdmin": "ایڈمن نے منسوخ کیا",
    "appointments.cancelAppointmentTitle": "ملاقات منسوخ کریں",
    "appointments.cancelConfirm":
      "کیا آپ واقعی یہ ملاقات منسوخ کرنا چاہتے ہیں؟",
    "appointments.noRefundPolicy": "رقم واپسی نہیں",
    "appointments.noRefundMessage":
      "مریض کی منسوخی پر رقم واپس نہیں کی جائے گی۔ ادائیگی واپس نہیں ہوگی۔",
    "appointments.reasonForCancellation": "منسوخی کی وجہ (اختیاری)",
    "appointments.cancellationPlaceholder":
      "ہمیں بتائیں آپ کیوں منسوخ کر رہے ہیں...",
    "appointments.noKeepIt": "نہیں، رکھیں",
    "appointments.yesCancel": "ہاں، منسوخ کریں",
    "appointments.cancelling": "منسوخ کیا جا رہا ہے...",
    "appointments.loadMore": "مزید لوڈ کریں",
    "appointments.noAppointmentsFound": "کوئی ملاقات نہیں ملی",
    "appointments.doctorUnavailable": "یہ ڈاکٹر فی الحال دستیاب نہیں ہے",
    "appointments.doctorBlockedMessage":
      "ڈاکٹر کو ایڈمن نے عارضی طور پر بلاک کر دیا ہے۔ آپ کی ملاقات کو دوبارہ شیڈول کرنے کی ضرورت ہو سکتی ہے۔",
    "appointments.noReasonProvided": "کوئی وجہ فراہم نہیں کی گئی",
    "appointments.rescheduledAppointment": "دوبارہ شیڈول کی گئی ملاقات",
    "appointments.status.upcoming": "آنے والی",
    "appointments.status.completed": "مکمل",
    "appointments.status.cancelled": "منسوخ",
    "appointments.onlineConsultation": "آن لائن مشاورت",
    "appointments.inPersonConsultation": "ذاتی ملاقات",
    "appointments.appointmentDetails": "ملاقات کی تفصیلات",
    "appointments.date": "تاریخ",
    "appointments.time": "وقت",
    "appointments.location": "جگہ",
    "appointments.reason": "وجہ",
    "appointments.viewSchedule": "شیڈول دیکھیں",
    "appointments.hideSchedule": "شیڈول چھپائیں",
    "appointments.viewFeedback": "فیڈ بیک دیکھیں",
    "appointments.hideFeedback": "فیڈ بیک چھپائیں",
    "appointments.bookAppointment": "ملاقات بک کریں",
    "call.callingForVideo": "...ویڈیو مشاورت کے لیے کال کر رہے ہیں",
    "call.accept": "قبول کریں",
    "call.decline": "مسترد کریں",
    "call.answerCallTitle": "کال کا جواب دیں",
    "call.answerCallConfirm": "کیا آپ واقعی کال کا جواب دینا چاہتے ہیں",
    "call.answer": "جواب دیں",
    "call.cancel": "منسوخ",
    "call.declineCallTitle": "کال مسترد کریں",
    "call.declineCallConfirm": "کیا آپ واقعی کال کو مسترد کرنا چاہتے ہیں",
    "call.documentSharingRequest": "دستاویزات شیئر کرنے کی درخواست",
    "call.documentSharingMessage":
      "آپ کی طبی دستاویزات دیکھنے کی اجازت چاہ رہے ہیں۔ کیا آپ اپنی دستاویزات شیئر کرنا چاہتے ہیں؟",
    "call.yes": "ہاں",
    "call.no": "نہیں",
    "call.documentRequestTitle": "دستاویز کی درخواست",
    "call.documentRequestMessage":
      "آپ کی طبی دستاویزات دیکھنے کی درخواست کی ہے۔ براہ کرم وہ دستاویزات منتخب کریں جو آپ شیئر کرنا چاہتے ہیں:",
    "call.noDocuments": "شیئر کرنے کے لیے کوئی دستاویز دستیاب نہیں",
    "call.shareSelected": "منتخب شیئر کریں",
    "call.documentsSharedTitle": "دستاویزات شیئر ہو گئیں",
    "call.documentsSharedMessage": "آپ نے کامیابی سے شیئر کیا",
    "call.documentsSharedWith": "ڈاکٹر کے ساتھ",
    "call.document": "دستاویز",
    "call.documents": "دستاویزات",
    "call.ok": "ٹھیک ہے",
    "call.prescriptionUploadedTitle": "نسخہ اپ لوڈ ہو گیا",
    "call.prescriptionUploadedMessage":
      "ڈاکٹر نے آپ کا نسخہ اپ لوڈ کر دیا ہے۔ آپ اسے اپنے دستاویزات سیکشن میں دیکھ سکتے ہیں۔",
    "call.completeConsultationTitle": "مشاورت مکمل کریں",
    "call.noPrescriptionWarning": "⚠️ ڈاکٹر نے ابھی تک نسخہ اپ لوڈ نہیں کیا۔",
    "call.completionRequestMessage":
      "نے مشاورت مکمل کرنے کی درخواست کی ہے۔ کیا آپ مشاورت مکمل کرنے پر متفق ہیں؟",
    "call.yes": "ہاں",
    "call.no": "نہیں",
    "call.consultationFinishedTitle": "مشاورت مکمل ہو گئی",
    "call.consultationFinishedMessage": "آپ کی مشاورت کامیابی سے مکمل ہو گئی۔",
    "call.endCallTitle": "کال ختم کریں",
    "call.noPrescriptionWarningEnd":
      "⚠️ ڈاکٹر نے ابھی تک نسخہ اپ لوڈ نہیں کیا۔",
    "call.endCallConfirmation": "کیا آپ واقعی اس کال کو ختم کرنا چاہتے ہیں",
    "call.cancel": "منسوخ کریں",
    "call.endCall": "کال ختم کریں",
    "call.callEndedTitle": "کال ختم ہو گئی",
    "call.callEndedMessage": "نے کال ختم کر دی۔",
    "call.callEndedByYouTitle": "کال ختم ہو گئی",
    "call.callEndedByYouMessage": "آپ نے کال ختم کر دی۔",
    "payments.title": "ادائیگیاں",
    "payments.subtitle":
      "اپنی ادائیگیوں، لین دین کی تاریخ اور ادائیگی کے طریقوں کا انتظام کریں",
    "payments.overview": "جائزہ",
    "payments.transactions": "لین دین",
    "payments.paymentMethods": "ادائیگی کے طریقے",
    "payments.requests": "درخواستیں",
    "payments.totalSpent": "کل خرچ",
    "payments.availableBalance": "دستیاب بیلنس",
    "payments.pendingPayments": "زیر التوا ادائیگیاں",
    "payments.paymentRequests": "ادائیگی کی درخواستیں",
    "payments.recentTransactions": "حالیہ لین دین",
    "payments.searchPlaceholder":
      "ڈاکٹر کے نام یا اپائنٹمنٹ آئی ڈی سے تلاش کریں...",
    "payments.filterByStatus": "حیثیت کے لحاظ سے فلٹر کریں",
    "payments.all": "تمام",
    "payments.completed": "مکمل",
    "payments.pending": "زیر التوا",
    "payments.refunded": "واپس",
    "payments.export": "ایکسپورٹ",
    "payments.exportCSV": "CSV میں ایکسپورٹ کریں",
    "payments.exportExcel": "Excel میں ایکسپورٹ کریں",
    "payments.noTransactions": "کوئی لین دین نہیں ملا",
    "payments.transactionId": "ٹرانزیکشن آئی ڈی",
    "payments.appointmentId": "اپائنٹمنٹ آئی ڈی",
    "payments.doctor": "ڈاکٹر",
    "payments.date": "تاریخ",
    "payments.amount": "رقم",
    "payments.mode": "قسم",
    "payments.status": "حیثیت",
    "payments.paymentMethod": "ادائیگی کا طریقہ",
    "payments.online": "آن لائن",
    "payments.inPerson": "ذاتی طور پر",
    "payments.addPaymentMethod": "ادائیگی کا طریقہ شامل کریں",
    "payments.noPaymentMethods":
      "ابھی تک کوئی ادائیگی کا طریقہ شامل نہیں کیا گیا",
    "payments.addFirstMethod":
      "ادائیگی کو آسان بنانے کے لیے اپنا پہلا ادائیگی کا طریقہ شامل کریں",
    "payments.bankAccount": "بینک اکاؤنٹ",
    "payments.mobileWallet": "موبائل والیٹ",
    "payments.accountNumber": "اکاؤنٹ نمبر",
    "payments.iban": "آئی بی اے این",
    "payments.phoneNumber": "فون نمبر",
    "payments.default": "ڈیفالٹ",
    "payments.setDefault": "ڈیفالٹ کے طور پر سیٹ کریں",
    "payments.edit": "ترمیم کریں",
    "payments.delete": "حذف کریں",
    "payments.addMethod": "طریقہ شامل کریں",
    "payments.cancel": "منسوخ کریں",
    "payments.save": "محفوظ کریں",
    "payments.methodType": "طریقہ کی قسم",
    "payments.methodName": "طریقہ کا نام",
    "payments.deleteConfirmTitle": "ادائیگی کا طریقہ حذف کریں",
    "payments.deleteConfirmMessage":
      "کیا آپ واقعی اس ادائیگی کے طریقہ کو حذف کرنا چاہتے ہیں؟",
    "payments.noRequests": "کوئی ادائیگی کی درخواست نہیں",
    "payments.allRequestsProcessed":
      "تمام ادائیگی کی درخواستوں پر کارروائی کی جا چکی ہے",
    "payments.appointmentType": "اپائنٹمنٹ کی قسم",
    "payments.reason": "وجہ",
    "payments.payNow": "ابھی ادا کریں",
    "payments.decline": "مسترد کریں",
    "payments.paid": "ادا کیا",
    "payments.declined": "مسترد",
    "payments.confirmPayment": "ادائیگی کی تصدیق کریں",
    "payments.selectPaymentMethod": "ادائیگی کا طریقہ منتخب کریں",
    "payments.confirmPaymentMessage": "کیا آپ واقعی ادا کرنا چاہتے ہیں",
    "payments.for": "کے لیے",
    "payments.declineRequest": "ادائیگی کی درخواست مسترد کریں",
    "payments.declineConfirmMessage":
      "کیا آپ واقعی اس ادائیگی کی درخواست کو مسترد کرنا چاہتے ہیں؟",
    "payments.success": "کامیابی",
    "payments.error": "خرابی",
    "payments.paymentSuccessMessage": "ادائیگی کامیابی سے مکمل ہو گئی!",
    "payments.paymentErrorMessage":
      "ادائیگی پر عمل کرنے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
    "payments.requestDeclined": "ادائیگی کی درخواست مسترد کر دی گئی",
    "payments.methodAdded": "ادائیگی کا طریقہ کامیابی سے شامل کیا گیا",
    "payments.methodDeleted": "ادائیگی کا طریقہ کامیابی سے حذف کیا گیا",
    "payments.methodUpdated": "ادائیگی کا طریقہ کامیابی سے اپ ڈیٹ کیا گیا",
    "payments.requestsTitle": "ادائیگی کی درخواستیں",
    "payments.requestsSubtitle":
      "فالو اپ مشاورت اور اضافی ادائیگی کی درخواستیں",
    "payments.appointmentDetails": "اپائنٹمنٹ کی تفصیلات",
    "payments.requested": "درخواست کی گئی",
    "payments.rescheduleReason": "دوبارہ شیڈول کرنے کی وجہ",
    "payments.noRequestsTitle": "کوئی ادائیگی کی درخواست نہیں",
    "payments.noRequestsMessage":
      "اس وقت آپ کے پاس کوئی زیر التوا ادائیگی کی درخواست نہیں ہے",
    "payments.paymentMethodsTitle": "ادائیگی کے طریقے",
    "payments.addMethodsPrompt":
      "اپائنٹمنٹس کے لیے 1-5 ادائیگی کے طریقے شامل کریں",
    "payments.maxLimitReached": "زیادہ سے زیادہ حد تک پہنچ گیا (5/5)",
    "payments.methodsAdded": "ادائیگی کے طریقے شامل کیے گئے",
    "payments.addNewMethod": "نیا ادائیگی کا طریقہ شامل کریں",
    "payments.selectBank": "بینک منتخب کریں",
    "payments.enterAccountNumber": "اکاؤنٹ نمبر درج کریں (10-20 ہندسے)",
    "payments.enterIBAN": "آئی بی اے این درج کریں (PK کے بعد 22 ہندسے)",
    "payments.selectWallet": "موبائل والیٹ منتخب کریں",
    "payments.enterPhoneNumber": "فون نمبر درج کریں (03XXXXXXXXX)",
    "payments.removeMethodTitle": "ادائیگی کا طریقہ ہٹائیں",
    "payments.removeMethodMessage":
      "کیا آپ واقعی اس ادائیگی کے طریقہ کو ہٹانا چاہتے ہیں؟ یہ عمل واپس نہیں ہو سکتا۔",
    "payments.followUp": "فالو اپ",
    "recommendations.bookingSuccess": "!اپائنٹمنٹ کامیابی سے بک ہو گئی",
    "recommendations.bookingSuccessMessage": "آپ کی ملاقات کی تصدیق ہو گئی ہے",
    "recommendations.date": "تاریخ",
    "recommendations.time": "وقت",
    "recommendations.close": "بند کریں",
    "recommendations.education": "تعلیم",
    "recommendations.certifications": "سرٹیفیکیشن",
    "recommendations.bio": "تعارف",
    "recommendations.workingHours": "کام کے اوقات",
    "recommendations.contact": "رابطہ کی معلومات",

    // Messages Page
    "messages.title": "پیغامات",
    "messages.subtitle": "اپنے ڈاکٹرز سے بات چیت کریں",
    "messages.searchDoctors": "ڈاکٹرز تلاش کریں...",
    "messages.noDoctorsFound": "کوئی ڈاکٹر نہیں ملا",
    "messages.noMessages": "ابھی تک کوئی پیغام نہیں۔ گفتگو شروع کریں!",
    "messages.typeMessage": "اپنا پیغام ٹائپ کریں...",
    "messages.selectDoctor": "پیغام بھیجنے کے لیے ڈاکٹر منتخب کریں",

    // Symptoms Page - Categories
    "symptoms.categoryGeneral": "عمومی علامات",
    "symptoms.categorySkin": "جلد کے مسائل",
    "symptoms.categoryStomach": "پیٹ اور ہاضمہ",
    "symptoms.categoryBreathing": "سانس اور سینہ",
    "symptoms.categoryUrinary": "پیشاب کے مسائل",
    "symptoms.categoryEyes": "آنکھیں اور بینائی",
    "symptoms.categoryBrain": "دماغ اور اعصاب",
    "symptoms.categoryBones": "ہڈیاں اور جوڑ",
    "symptoms.categoryMental": "ذہنی صحت",
    "symptoms.categoryLiver": "جگر کی علامات",
    "symptoms.categoryHeart": "دل سے متعلق",
    "symptoms.categoryHormonal": "ہارمون کے مسائل",
    "symptoms.categoryRectal": "مقعد کے مسائل",
    "symptoms.categoryOther": "دیگر علامات",

    // Symptoms Page - Interface
    "symptoms.title": "علامات بتائیں",
    "symptoms.subtitle":
      "اپنی علامات بتائیں اور موزوں ڈاکٹر کا مشورہ حاصل کریں",
    "symptoms.selectedSymptoms": "آپ کی منتخب علامات",
    "symptoms.clearAll": "سب ہٹائیں",
    "symptoms.browseSymptoms": "علامات دیکھیں",
    "symptoms.searchPlaceholder":
      "علامات تلاش کریں (مثال: بخار، سر درد، کھانسی...)",
    "symptoms.noSymptomsFound": "کوئی علامت نہیں ملی",
    "symptoms.clearSearch": "تلاش ختم کریں",
    "symptoms.selected": "منتخب",
    "symptoms.symptoms": "علامات",
    "symptoms.of": "میں سے",
    "symptoms.howItWorks": "کیسے استعمال کریں",
    "symptoms.step1": "اپنی علامات منتخب کریں یا تلاش کریں",
    "symptoms.step2": "اوپر اپنی منتخب علامات چیک کریں",
    "symptoms.step3": "تجزیہ کے لیے جمع کریں",
    "symptoms.readyToSubmit": "جمع کریں!",
    "symptoms.youveSelected": "آپ نے",
    "symptoms.symptom": "علامت",
    "symptoms.getRecommendation": "ڈاکٹر تلاش کریں",
    "symptoms.analyzing": "جانچ جاری ہے...",
    "symptoms.findingBest": "آپ کے لیے بہترین ڈاکٹر تلاش کر رہے ہیں",
    "symptoms.confirmTitle": "علامات کی تصدیق",
    "symptoms.confirmMessage":
      "آپ نے یہ علامات منتخب کی ہیں۔ ڈاکٹر کی سفارش کے لیے تصدیق کریں:",
    "symptoms.total": "کل",
    "symptoms.cancel": "واپس",
    "symptoms.confirmButton": "تصدیق کریں",
    "symptoms.predictionError": "خرابی",
    "symptoms.recommendedSpecialist": "موزوں ڈاکٹر",
    "symptoms.basedOnSymptoms": "آپ کی علامات کے مطابق، آپ کو ملنا چاہیے:",
    "symptoms.found": "ملے",
    "symptoms.doctor": "ڈاکٹر",
    "symptoms.doctors": "ڈاکٹر",
    "symptoms.available": "موجود",
    "symptoms.clickToSearch":
      "اس شعبے میں ڈاکٹر تلاش کرنے کے لیے نیچے کلک کریں",
    "symptoms.viewRankedDoctors": "ڈاکٹرز دیکھیں",
    "symptoms.searchForDoctors": "ڈاکٹر تلاش کریں",
    "symptoms.close": "بند کریں",
    "symptoms.ok": "ٹھیک ہے",
    "symptoms.rankedDoctors": "موزوں ڈاکٹرز",
    "symptoms.specialty": "شعبہ",
    "symptoms.noDoctorsAvailable": "ڈاکٹر موجود نہیں",
    "symptoms.couldntFind": "اس شعبے میں کوئی ڈاکٹر نہیں ملا",
    "symptoms.atMoment": "ابھی۔",
    "symptoms.whatCanYouDo": "آپ کیا کر سکتے ہیں؟",
    "symptoms.tryAgainLater": "بعد میں کوشش کریں - نئے ڈاکٹر شامل ہو سکتے ہیں",
    "symptoms.browseAll": "تمام ڈاکٹر دیکھنے کے لیے سفارشات پر جائیں",
    "symptoms.contactSupport": "فوری مدد کے لیے سپورٹ سے رابطہ کریں",
    "symptoms.showing": "دکھا رہے ہیں",
    "symptoms.rating": "ریٹنگ",
    "symptoms.experience": "تجربہ",
    "symptoms.year": "سال",
    "symptoms.years": "سال",
    "symptoms.matchScore": "مماثلت",
    "symptoms.email": "ای میل",
    "symptoms.phone": "فون",
    "symptoms.consultationFee": "فیس",
    "symptoms.viewDetailsBook": "تفصیل دیکھیں اور بک کریں",
    "symptoms.review": "رائے",
    "symptoms.reviews": "رائے",

    // Specialty Translations (Core Specialties)
    "specialty.Allergist": "الرجی کا ماہر",
    "specialty.Cardiologist": "دل کا ماہر",
    "specialty.Common Cold": "عام زکام",
    "specialty.Dermatologist": "جلد کا ماہر",
    "specialty.Endocrinologist": "ہارمونز کا ماہر",
    "specialty.Gastroenterologist": "معدے اور ہاضمے کا ماہر",
    "specialty.Gynecologist": "نسائی امراض کا ماہر",
    "specialty.Hepatologist": "جگر کا ماہر",
    "specialty.Internal Medicine": "باطنی امراض کا ماہر",
    "specialty.Neurologist": "دماغ اور اعصاب کا ماہر",
    "specialty.Osteoarthritis": "ہڈیوں کے جوڑوں کا ماہر",
    "specialty.Osteopathic": "ہڈیوں کا معالج",
    "specialty.Otolaryngologist": "کان، ناک، گلے کا ماہر",
    "specialty.Pediatrician": "بچوں کا ڈاکٹر",
    "specialty.Phlebologist": "رگوں کا ماہر",
    "specialty.Pulmonologist": "پھیپھڑوں کا ماہر",
    "specialty.Rheumatologist": "جوڑوں کے امراض کا ماہر",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("english");

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "english" ? "urdu" : "english"));
  };

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  // Set dir attribute on document.documentElement for RTL support
  useEffect(() => {
    if (language === "urdu") {
      document.documentElement.setAttribute("dir", "rtl");
      document.documentElement.classList.add("rtl");
    } else {
      document.documentElement.setAttribute("dir", "ltr");
      document.documentElement.classList.remove("rtl");
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div className={language === "urdu" ? "rtl" : "ltr"}>{children}</div>
    </LanguageContext.Provider>
  );
};
